### ISSUE TITLE
Range is not an iterator

### ISSUE THREAD

**Issue by lijeffreytli** [adambard/learnxinyminutes-docs#1323]
In the Learn Python in Y minutes, it says that Range is a generator, which it's technically not. Clearer distinctions should be made.

**Comment by vendethiel** [comment]
I don't know much about Python. If you do, could you please submit a pull request? Thanks!

**Comment by levibostian** [comment]
It "generates" an array and returns it. Maybe that is what the document means?

To me, range is a function, typically used with loops because of how handy it is for a finite set of data, that returns an array from min to max. 

So yes, I agree it is not a generator, it's a function. Not sure we have to go that technical with explaining it, but would be great to change it. 

Is this in the python and python3 docs both? Make a PR please and mention me in it. I'll help you out critique it and get it merged in.

**Comment by aayushranaut** [comment]
# Note range is a generator too. Creating a list 1-900000000 would take lot of
# time to be made

I think this line is totally irrelevant to the context of generators and can be truncated entirely. What do you think @levibostian ?

**Comment by levibostian** [comment]
I agree @aayushranaut
