### ISSUE TITLE
[Python3] Intersection typo

### ISSUE THREAD

**Issue by tsunammis** [adambard/learnxinyminutes-docs#2038]
Hello,

I found a small typo inside the intersection documentation for Python3

```python
# Do set intersection with &
other_set = {3, 4, 5, 6}
filled_set & other_set  # => {3, 4, 5}
```

The result of `filled_set & other_set`for me is equals to `{3, 4}` instead of `{3, 4, 5}`

Regards,

**Comment by divayprakash** [comment]
The code you're referring to is -
`filled_set.add(5)  # filled_set is now {1, 2, 3, 4, 5}`
`# Do set intersection with &`
`other_set = {3, 4, 5, 6}`
`filled_set & other_set  # => {3, 4, 5}`

I think you made a typo when running this code because as you can see from the code, both the `filled_set` and the `other_set` contain the elements `{3, 4, 5}` in common which is then naturally the result of their intersection. So there isn't a typo here to correct!

**Comment by divayprakash** [comment]
@vendethiel @adambard 
Issue can be closed.

**Comment by vendethiel** [comment]
indeed.
