### ISSUE TITLE
[tcl/en] Broken TCL syntax highlight

### ISSUE THREAD

**Issue by lewtds** [adambard/learnxinyminutes-docs#2569]
Might be related to #1214

![screenshot at 2016-11-15 04-53-20](https://cloud.githubusercontent.com/assets/1055960/20291523/9046943a-aaef-11e6-8aa3-541c81eda5a6.png)

**Comment by samcv** [comment]
Hmm it seems to be caused by this line:
`# command, use the expansion operator, "{*}".`

I have a branch that uses Pygments instead of Rouge (what the site currently uses). It may be possible we could switch over because it could get us syntax highlighting for many more languages if @adambard thinks it's a good idea. I will check if it works in Pygments and report back.

**Comment by adambard** [comment]
I am not opposed, so long as everything works

**Comment by samcv** [comment]
Cool. There shouldn't be any issues, but when I have time I will make make sure all things are in order.

@lewtds with Pygments it works except it fails when getting to this crazy line:

![screenshot_20161114_194908](https://cloud.githubusercontent.com/assets/20145557/20292590/a800411c-aaa3-11e6-8748-27fb97c8338d.png)

**Comment by lewtds** [comment]
Github's internal highlighter works fine for both locations.
https://github.com/adambard/learnxinyminutes-docs/blob/master/tcl.html.markdown

![screenshot at 2016-11-15 07-39-55](https://cloud.githubusercontent.com/assets/1055960/20294444/e568656c-ab06-11e6-91c2-da0a30cd9491.png)

![screenshot at 2016-11-15 07-40-43](https://cloud.githubusercontent.com/assets/1055960/20294459/ef8c4324-ab06-11e6-8017-bd4d2679c493.png)
