### ISSUE TITLE
The new Janet page is 404

### ISSUE THREAD

**Issue by uvtc** [adambard/learnxinyminutes-docs#4000]
PR #3998 for the new [Janet page](https://learnxinyminutes.com/docs/janet/) was recently accepted, and it's listed on [the homepage](https://learnxinyminutes.com/), but the specific page itself is not found on the site.

**Comment by kevinnls** [comment]
@mxschumacher #4001 didn't fix it. sorry please reopen the issue

**Comment by kevinnls** [comment]
the problem is that [Pygments](https://pygments.org/) the syntax highlighting engine used by LXIYM doesn't yet have support for Janet.

i was able to build the page locally by simply **removing the explicit syntax declaration at ln18** but as expected, this leaves the code with generic syntax highlighting

i can't suggest any proper solution for this because i'm not sure how [LXIYM-site](//github.com/adambard/learnxinyminutes-site "the site repo") manages the formatting of syntax

<p align="center"><img width="50%" alt="removed explicit spect janet" src="https://user-images.githubusercontent.com/57634663/90759970-d3ba6480-e2fe-11ea-9d7b-9c33743fdbfa.png"></img></p>

<p align="center"><img width="75%" alt="locally built page" src="https://user-images.githubusercontent.com/57634663/90761675-60662200-e301-11ea-922f-4b4074c36ff7.png"></img></p>

**Comment by kevinnls** [comment]
attaching the error message for anyone interested

#### MentosError at /docs/janet/
```Traceback (most recent call last): 
File "/var/lib/gems/2.7.0/gems/pygments.rb-1.2.1/lib/pygments/mentos.py", 
	line 303, in start res = self.get_data(method, lexer, args, kwargs, text) 
File "/var/lib/gems/2.7.0/gems/pygments.rb-1.2.1/lib/pygments/mentos.py", 
	line 171, in get_data res = self.highlight_text(text, lexer, formatter_name, args, _convert_keys(opts)) 
File "/var/lib/gems/2.7.0/gems/pygments.rb-1.2.1/lib/pygments/mentos.py", 
	line 122, in highlight_text lexer = self.return_lexer(lexer, args, kwargs, code) 
File "/var/lib/gems/2.7.0/gems/pygments.rb-1.2.1/lib/pygments/mentos.py", 
	line 79, in return_lexer return lexers.get_lexer_by_name(lexer, **inputs) 
File "/var/lib/gems/2.7.0/gems/pygments.rb-1.2.1/vendor/pygments-main/pygments/lexers/__init__.py", 
	line 115, in get_lexer_by_name raise ClassNotFound('no lexer for alias %r found' % _alias) 

ClassNotFound: no lexer for alias 'janet' found
```

**Comment by uvtc** [comment]
I know that rouge supports Janet. Is there any compatibility between rouge and pygments?

**Comment by kevinnls** [comment]
@uvtc being the author of the issue, are you able to reopen it?

**Comment by uvtc** [comment]
Hi @kevinnls , thanks. No, I don't see a way I can re-open this issue.

**Comment by kevinnls** [comment]
i'm sure @mxschumacher will reopen soon. no worries. we'll get to a solution asap. again, thanks for the contribution!

i only got as far as the intro but i loved it

**Comment by uvtc** [comment]
Submitted the PR for Janet support in pygments.

**Comment by kevinnls** [comment]
@mxschumacher until the new lexer and the next release of Pygments, i think we need a quick fix to un-404 this page...

@uvtc we could perhaps change the explicit syntax highlighting to something similar/something plain (is there one?) and add a line about syntax highlighting being in the works. what you think?

**Comment by Yam76** [comment]
You can probably bootleg the clojure or common lisp highlighting and just mention that Janet syntax highlighting hasn't arrived yet.

**Comment by uvtc** [comment]
I'm sorry to have dropped the ball on this. Work got extremely busy and my git-fu is not very strong, and so I haven't finished the changes requested for the pygments lexer. It's basically ready except for a minor tweak that was requested, as well as a test.

**Comment by uvtc** [comment]
Currently stalled at https://github.com/pygments/pygments/pull/1519 until I can make more time to return to this, or until someone else picks it up and finishes it up.

**Comment by jaawerth** [comment]
@uvtc For what it's worth, I'm not familiar enough with janet to know all the syntactic differences and what possible edge cases they might cause with pygments, but:

As a temporary workaround to get this unblocked, it might be worth trying the same trick both [janet](https://github.com/janet-lang/janet/blob/c3f770da27107d2d9f13e81e199d277799b12b68/.gitattributes) and [fennel](https://github.com/bakpakin/Fennel/blob/4ad5cfe3f76e4b3d1014244e83d8b7e366667fbe/.gitattributes#L6-L7) use for github/linguist, namely tricking pygments into using the clojure highlighter. It's a little hacky, but since both languages take inspiration from clojure syntax (`[]`, `{}`, `:foo`, etc), I've seen it work well enough (better than nothing, anyway) more often than not.

Just a thought!

**Comment by uvtc** [comment]
Since the Janet page is currently using Python syntax highlighting and no longer 404, closing this.

At some point, when Pygments has Janet support, will just change the syntax-hl directive in the doc to use Janet instead of Python.

Thanks all!
