### ISSUE TITLE
[Request] [zig/en-us] 

### ISSUE THREAD

**Issue by Mouvedia** [adambard/learnxinyminutes-docs#4005]
website: https://ziglang.org/
documentation: https://ziglang.org/documentation/master/
repository: https://github.com/ziglang/zig/

**Comment by Mouvedia** [comment]
I started working on this one. I am 30% done; should I open a draft PR?

**Comment by ratfactor** [comment]
@Mouvedia I should be able to lend a hand in a bit if you could use one? ✋

**Comment by Mouvedia** [comment]
@ratfactor check discord

**Comment by GilDev** [comment]
Any news? 🙂

**Comment by Mouvedia** [comment]
@GilDev https://github.com/Mouvedia/zig-examples
Ill finish it eventually.

**Comment by kaatt** [comment]
Also looking for this!

**Comment by KaneRoot** [comment]
Hello everyone.

I also started to work on it and end up pushing a PR: https://github.com/adambard/learnxinyminutes-docs/pull/4293

@Mouvedia I read your version. It was both too exhaustive and not enough explained for me.
For example, I like a few things you want to introduce, like the unrolling of "for" at compile-time. Having the possibility to print every elements of a structure at compile-time with `comptimePrint` is nice. But you introduced that in the worst possible way, without any comment, while presenting other concepts (also without any comments…): `@setEvalBranchQuota`, `@field`, etc.

I don't think anyone wants to read learnxinyminutes to get all possible minor details of a language. Sometimes you have 10 lines of code without any comment. Even for an experienced developer that's not enjoyable.

Also, there are a lot missing. At this point, I just wrote my own version.

Feel free to improve on my PR.
There a few things left I would like to show, such as:
- The integration with the C language, which clearly is a big perk of the language.
- The build system, which is used to compile without dependencies on the host even on Windows.
- Async functions.

After that, I doubt to provide more. It would feel a bit too much exhaustive.
What do you think?

Thanks everyone.

**Comment by Mouvedia** [comment]
> But you introduced that in the worst possible way

…thanks?

> At this point, I just wrote my own version.

Godspeed.

> Feel free to improve on my PR.

Ill let you do your thing.

> What do you think?

Do it for the `0.9.0`; mine was for the `0.7.1`.

**Comment by KaneRoot** [comment]
> Do it for the `0.9.0`; mine was for the `0.7.1`.

Yep, I tested my examples (most of them at least) with the latest 0.9.0 version.

> I saw you reused some of my examples. If it amounts to more than 30%, adding me as a contributor could be considerate on your part.

Based on your document:
- I explained the 3 different types of comments, which I firstly didn't think about;
- I reused your example of switch with a range as a pattern;
- I reused an example of union;
- I reused your idea of cardinal directions.
Even being generous, that's about 25 lines for a page that is 980 lines. I also copied a few examples from the official documentation, but almost everything is original. I say this because I don't want you to feel ripped off.
Also, despite this, I can still add you as a contributor if you want, I don't care about this kind of stuff.

(And sorry if I appeared a bit rude earlier, that wasn't intended.)
