### ISSUE TITLE
[Cairo/en] is broken

### ISSUE THREAD

**Issue by Darlington02** [adambard/learnxinyminutes-docs#4606]
Few days ago I finally got my PR to merge Cairo into LXIYM thanks to @mribeirodantas @vendethiel, but the page appears to be broken, as it throws a 404 when I try to access it.

Would appreciate if this is fixed 🙏🏽

![Screenshot 2023-02-21 at 09 36 27](https://user-images.githubusercontent.com/75126961/221837710-38ba022c-8179-4485-8b37-c9585809d69d.png)

**Comment by nbehrnd** [comment]
Though this is addressed by the final four lines / the last major point in file
`CONTRIBUTIONS.md`, I lack an idea (hence, experience) how to implement it.

**Comment by mribeirodantas** [comment]
Yeah, I don't remember of ever being able to preview it locally either 😞

**Comment by nbehrnd** [comment]
By now the address https://learnxinyminutes.com/docs/cairo/ is functional:

![2023-02-28_cairo_online](https://user-images.githubusercontent.com/19709084/221980597-63a646dc-f932-494c-96f9-4870ec0338e9.png)

*Speculation:* The syntax highlighter is unaware about `Cairo` as language.  If is is [pygments](https://github.com/pygments/pygments), one possibly could compile a listing of the reserved words, either create, or request creation of an additional style.

@Darlington02 
Outside this project of `learnxinyminutes`: In the English edition of Wikipedia, the page dedicated to list meanings of `cairo`  doesn't list it as language in section [computing](https://en.wikipedia.org/wiki/Cairo_(disambiguation)#Computing), nor Wikipedia's [compilation of programming languages](https://en.wikipedia.org/wiki/List_of_programming_languages#C), nor [rosettacode](https://rosettacode.org/wiki/Category:Programming_Languages).  Without background in CS, nor blockchain, these are among  the online addresses I would visit on first encounter with a new programming language.  Do you think such an additional presentation were welcome among the community of `cairo` developers & users?  The question is addressed here because there apparently is a user forum [on discord](https://starknet.io/discord), but its content is not public (contrasting to e.g., discussion boards around [avogadro](https://discuss.avogadro.cc/), or [fortran-lang](https://fortran-lang.discourse.group/)), which is a bit unexpected for a project hosted on [GitHub](https://github.com/starkware-libs/cairo-lang).

**Comment by mribeirodantas** [comment]
Ok, so I did right by removing the syntax highlight for Cairo. Thanks, @nbehrnd !

**Comment by Darlington02** [comment]
> By now the address https://learnxinyminutes.com/docs/cairo/ is functional:
> 
> ![2023-02-28_cairo_online](https://user-images.githubusercontent.com/19709084/221980597-63a646dc-f932-494c-96f9-4870ec0338e9.png)
> 
> _Speculation:_ The syntax highlighter is unaware about `Cairo` as language. If is is [pygments](https://github.com/pygments/pygments), one possibly could compile a listing of the reserved words, either create, or request creation of an additional style.
> 
> @Darlington02 Outside this project of `learnxinyminutes`: In the English edition of Wikipedia, the page dedicated to list meanings of `cairo` doesn't list it as language in section [computing](https://en.wikipedia.org/wiki/Cairo_(disambiguation)#Computing), nor Wikipedia's [compilation of programming languages](https://en.wikipedia.org/wiki/List_of_programming_languages#C), nor [rosettacode](https://rosettacode.org/wiki/Category:Programming_Languages). Without background in CS, nor blockchain, these are among the online addresses I would visit on first encounter with a new programming language. Do you think such an additional presentation were welcome among the community of `cairo` developers & users? The question is addressed here because there apparently is a user forum [on discord](https://starknet.io/discord), but its content is not public (contrasting to e.g., discussion boards around [avogadro](https://discuss.avogadro.cc/), or [fortran-lang](https://fortran-lang.discourse.group/)), which is a bit unexpected for a project hosted on [GitHub](https://github.com/starkware-libs/cairo-lang).

Yes this is true. It's a relatively new language with a growing community. More efforts would be put towards addressing the aforementioned in the coming few months after the release of Cairo 1.0
