### ISSUE TITLE
Angular js - code file not found

### ISSUE THREAD

**Issue by sohang3112** [adambard/learnxinyminutes-docs#5172]
Code file url is invalid for AngularJS (gives 404 error): both in [English](https://learnxinyminutes.com/docs/angularjs/) page ([learnangular.html](https://learnxinyminutes.com/docs/files/learnangular.html)) and [Chinese](https://learnxinyminutes.com/docs/zh-cn/angularjs-cn/) page ([learnangular-cn.html](https://learnxinyminutes.com/docs/files/learnangular-cn.html)).

**Comment by sohang3112** [comment]
@adambard BTW how exactly do these code pages work (i.e., where are they stored in the repository??) For example, [jquery.js](https://learnxinyminutes.com/docs/files/jquery.js) code page exists but I can't find any file named jquery.js in the repository!

**Comment by verhovsky** [comment]
Fixed in https://github.com/adambard/learnxinyminutes-docs/commit/572827b39f7a511b33a4aaa64438960c386343e2 and that commit should also answer your question. The source code is extracted by this code 

https://github.com/adambard/learnxinyminutes-site/blob/19e4324b6a3feefff51946230e2471bcb6c4a6a1/config.rb#L254-L269

and the filename it's saved as is the `filename:` property in the frontmatter (the YAML before the markdown begins in the files in this repository)

**Comment by sohang3112** [comment]
@verhovsky For Angularjs english page the problem is fixed but for the chinese page still the same broken code link is showing (even after disabling cache in browser), please check it:

![Angularjs Chinese page screenshot](https://github.com/user-attachments/assets/f3e0f5c1-068a-4629-aea6-156a45cb7ad9)

![Angualarjs Code page](https://github.com/user-attachments/assets/102f50df-2f18-4975-a23e-a09dbe8cfb8c)
