### ISSUE TITLE
Rust tutorial should discuss type inference more.

### ISSUE THREAD

**Issue by jackhooper** [adambard/learnxinyminutes-docs#860]
At present, Rust's type inference only gets a very brief mention. I don't know Rust very well, but most of the example code on the Rust website uses type inference rather than explicit type annotations, so it would appear that this is the idiomatic thing. 

Another issue with defaulting to explicit type annotations is that people who are first introduced to the language via Learn X in Y Minutes may end up assuming that explicit type annotations are compulsory in Rust, and there are a lot of programmers out there who would be put off by that.

**Comment by P1start** [comment]
The type annotations are there so that when a new concept is introduced, the type for it can be introduced at the same time. A quick `grep` through the rust.html.markdown file shows that ~52% of variable declarations have an explicit type annotation. While it certainly is true that type annotations in real-world Rust code are quite rarely needed, I think in most cases where type annotations are used, they are necessary to show how to write the type of whatever new thing is being introduced.

I plan to update the tutorial for Rust 1.0 Alpha anyway, so I’ll probably elaborate a little on type inference when I do that.
